### ISSUE TITLE
How to Guide for Using loltinder on Microsoft

### ISSUE THREAD

**Issue by Voluntaryism** [rgr4y/loltinder#2]
The instructions for this script are pretty awful and exacerbated when using microsoft, so here's the guide for ameliorating those shortcomings.

https://docs.google.com/document/d/1awpMxfVtWY_-29gPmsjAW4B9eUTq4O-1vDgHu4d9P_4/edit

**Comment by Wenger786** [comment]
followed instructions in https://docs.google.com/document/d/1awpMxfVtWY_-29gPmsjAW4B9eUTq4O-1vDgHu4d9P_4/edit but they also become unclear drom "Copy file app.js and package.json to place in C:\Users[Username]\AppData\Roaming" onwards.

**Comment by basstwo2k** [comment]
all the other steps are very clear and easy to follow, apart from the following two:
open package.json file in wordpad and do what changes? can anyone explain? 
follow comment on tinderjs in package.json file ? and do what changes ? are you refer to the followings:

You can point tinderbots dependency for tinderjs to the github branch.

Go into node_modules/tinderbot
Open package.json
Change tinderjs to: "tinderjs": "git+http://github.com/alkawryk/tinderjs.git#master",
Then run npm install in node_modules/tinderbot

**Comment by basstwo2k** [comment]
i am the total amateur here, please help me.

when i open package.json in wordpad, it looks like this to me:

{
  "name": "loltinder",
  "version": "0.0.1",
  "dependencies": {},
  "devDependencies": {
    "underscore": "~1.6.0",
    "tinderbot": "*"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}

what should i change to make it working?

**Comment by JamesTsetsekas** [comment]
i got the same issue when trying to change tinderjs it deoesent mention tinderjs atl in the json
