### ISSUE TITLE
Not getting any Match

### ISSUE THREAD

**Issue by alokc83** [rgr4y/loltinder#5]
It seemsd when i run node app.js NUMBERID "Facebook string" 
i get to reach here code wise 
console.log('###########################');
console.log('Token: ' + bot.access_token);
console.log('FB ID: ' + bot.facebook_id);
console.log('CURL: curl -X POST --data "facebook_token='+bot.access_token+'&facebook_id='+bot.facebook_id+'" https://api.gotinder.com/auth');
console.log('###########################');

but I dont get any Matched String on console. 
Am I doing something wrong ?

**Comment by simon0356** [comment]
Is that always worked ? i have access denied response on first post request
